language: php

php:
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install
  - wget https://phar.phpunit.de/phpunit.phar
  - chmod 777 ./phpunit.phar
  - npm install -g phantomjs
  - npm install -g casperjs

script:
  - ./phpunit.phar
